import os
os.chdir(f"/home/xlab-app-center")
os.system(f"apt update")
os.system(f"apt-get --assume-yes install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6")
os.system(f"apt-get --assume-yes install git-lfs")
os.system(f"git lfs install")
os.system(f"apt-get --assume-yes install wget")
os.system(f"git clone https://huggingface.co/spaces/vinthony/SadTalker /home/xlab-app-center/SadTalker")
os.chdir(f"/home/xlab-app-center/SadTalker")
os.system(f"pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113")
os.system(f"apt-get --assume-yes install ffmpeg")
os.system(f"pip install -r requirements.txt")
os.system(f"pip install TTS")
os.system(f"pip install gradio")
os.system(f"pip install gradio_client")
os.system(f"git reset --hard")
os.system(f"python app.py --theme dark")

